name: CI-FINAL-WIN-V2

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Windows EXE
    runs-on: windows-2022
    strategy:
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install NASM
        uses: ilammy/setup-nasm@v1

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: vcpkg setup
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '120deac3062162151622ca4860575a33844ba10b'

      - name: Install vcpkg dependencies
        shell: bash
        run: |
          # Устанавливаем полный набор кодеков: vpx, opus, aom (AV1), dav1d, yuv и zlib
          $VCPKG_ROOT/vcpkg install libvpx libyuv opus libaom dav1d zlib --triplet x64-windows-static --classic

      - name: Cargo Build
        shell: bash
        env:
          RS_ID_SERVER: ${{ secrets.RS_ID_SERVER }}
          RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg
          VCPKGRS_DYNAMIC: 0
        run: |
          # Собираем релизную версию
          cargo build --release --target x86_64-pc-windows-msvc

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RustDesk-Windows-Custom
          path: target/x86_64-pc-windows-msvc/release/*.exe
